'use client';

import { useState } from 'react';

const FAQS = [
  {
    question: 'Is sending a demand letter to my landlord legal?',
    answer:
      "Absolutely. Tenants have a legal right to assert their rights in writing, and doing so is encouraged by housing authorities and tenancy tribunals in every jurisdiction we cover. A formal written demand creates a paper trail and is often the first required step before filing a complaint with a housing authority. Writing to your landlord in no way jeopardizes your tenancy — in fact, it is often necessary to establish that you gave proper notice before seeking legal remedies.",
  },
  {
    question: 'Can my landlord retaliate against me for sending this letter?',
    answer:
      "Landlord retaliation for exercising tenant rights is illegal in virtually every jurisdiction TenantShield covers. In Ontario, Section 83 of the Residential Tenancies Act protects tenants from eviction filed in response to asserting their rights. In California, Civil Code § 1942.5 explicitly prohibits retaliatory evictions and rent increases. If your landlord attempts to retaliate, document everything — it strengthens your legal position significantly. TenantShield letters are specifically designed to put your landlord on notice of their obligations, not to provoke conflict.",
  },
  {
    question: 'What if my landlord ignores the letter?',
    answer:
      "Ignoring a formal written demand strengthens your case. Each TenantShield letter includes specific escalation language that names the appropriate authority — such as the Landlord and Tenant Board (Ontario), the Tribunal administratif du logement (Quebec), or local Code Enforcement (California). If your landlord does not respond, your next step is to file with that body, and your letter serves as evidence that you provided proper written notice. In some jurisdictions, sending the letter is a legal prerequisite to filing a complaint — so doing it right the first time matters.",
  },
  {
    question: 'Will this actually work?',
    answer:
      "Many landlords resolve issues quickly once they receive a formal letter citing specific laws and naming regulatory bodies — because it signals that the tenant is informed and serious. While we cannot guarantee any specific outcome, the letters generated by TenantShield are deliberately modeled on the language used by paralegals and legal aid clinics. They are substantively different from informal complaints or text messages, and they create a legal paper trail that supports any future formal complaint or tribunal application.",
  },
  {
    question: 'Is TenantShield a law firm? Is this legal advice?',
    answer:
      "No. TenantShield is a document preparation service that generates template-based demand letters. We are not a law firm and the letters generated do not constitute legal advice. If your situation involves potential safety risks, threatened eviction, a history of conflict with your landlord, or any other complexity, we strongly recommend consulting a licensed lawyer, paralegal, or tenant rights organization in your jurisdiction. Many jurisdictions offer free or low-cost legal aid for tenants.",
  },
  {
    question: 'How is this different from just sending an email to my landlord?',
    answer:
      "A formal demand letter does several things an informal email cannot: it cites specific statutory provisions and housing codes by name and section number; it establishes an explicit legal deadline; it names the specific regulatory body where a complaint will be filed; and it signals — through its format and language — that the sender is prepared to escalate. Courts and tribunals generally expect to see a formal written notice before entertaining a complaint. An email saying 'please fix the mold' typically does not meet that standard.",
  },
];

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border-b border-gray-200 last:border-0">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-start justify-between py-5 text-left gap-4"
        aria-expanded={open}
      >
        <span className="font-semibold text-navy-900 text-base">{question}</span>
        <span
          className={`flex-shrink-0 w-6 h-6 rounded-full bg-gray-100 flex items-center justify-center transition-transform duration-200 ${
            open ? 'rotate-180' : ''
          }`}
        >
          <svg className="w-3.5 h-3.5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
          </svg>
        </span>
      </button>
      {open && (
        <div className="pb-5">
          <p className="text-gray-600 leading-relaxed text-sm">{answer}</p>
        </div>
      )}
    </div>
  );
}

export default function FAQ() {
  return (
    <section id="faq" className="py-16 sm:py-24 px-4 bg-gray-50">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold text-navy-900 mb-3">
            Frequently Asked Questions
          </h2>
          <p className="text-gray-500 text-lg">
            Common questions from tenants before they send their first letter.
          </p>
        </div>

        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm divide-y divide-gray-200 px-6 sm:px-8">
          {FAQS.map((faq) => (
            <FAQItem key={faq.question} question={faq.question} answer={faq.answer} />
          ))}
        </div>
      </div>
    </section>
  );
}
