import Link from 'next/link';
import { Shield } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="bg-navy-900 text-white mt-auto">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-12">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 mb-8">
          <div>
            <div className="flex items-center gap-2 mb-3">
              <div className="w-7 h-7 bg-white/10 rounded-lg flex items-center justify-center">
                <Shield className="w-4 h-4 text-white" />
              </div>
              <span className="text-lg font-bold">TenantShield</span>
            </div>
            <p className="text-sm text-gray-400">
              Helping tenants assert their rights with professionally worded, legally-informed demand letters.
            </p>
          </div>

          <div>
            <h4 className="text-sm font-semibold uppercase tracking-wider text-gray-400 mb-3">Jurisdictions</h4>
            <ul className="space-y-2 text-sm text-gray-300">
              <li><Link href="/wizard" className="hover:text-white transition-colors">Ontario Tenant Rights</Link></li>
              <li><Link href="/wizard" className="hover:text-white transition-colors">Quebec Tenant Rights</Link></li>
              <li><Link href="/wizard" className="hover:text-white transition-colors">California Tenant Rights</Link></li>
              <li><Link href="/wizard" className="hover:text-white transition-colors">New York Tenant Rights</Link></li>
            </ul>
          </div>

          <div>
            <h4 className="text-sm font-semibold uppercase tracking-wider text-gray-400 mb-3">Common Issues</h4>
            <ul className="space-y-2 text-sm text-gray-300">
              <li><Link href="/wizard" className="hover:text-white transition-colors">Mold &amp; Moisture Letters</Link></li>
              <li><Link href="/wizard" className="hover:text-white transition-colors">No Heat Complaints</Link></li>
              <li><Link href="/wizard" className="hover:text-white transition-colors">Pest Infestation Letters</Link></li>
              <li><Link href="/wizard" className="hover:text-white transition-colors">Broken Lock Demand Letters</Link></li>
            </ul>
          </div>
        </div>

        <div className="border-t border-white/10 pt-6">
          <p className="text-xs text-gray-500 text-center leading-relaxed">
            <strong className="text-gray-400">Legal Disclaimer:</strong> TenantShield provides document preparation assistance and is not a law firm.
            The letters generated by this service do not constitute legal advice and do not create an attorney-client relationship.
            For legal advice specific to your situation, please consult a qualified attorney or tenant rights organization in your jurisdiction.
          </p>
          <div className="flex items-center justify-center gap-4 mt-4">
            <Link href="/terms" className="text-xs text-gray-600 hover:text-gray-400 transition-colors">Terms of Service</Link>
            <span className="text-gray-700">·</span>
            <Link href="/privacy" className="text-xs text-gray-600 hover:text-gray-400 transition-colors">Privacy Policy</Link>
            <span className="text-gray-700">·</span>
            <a href="mailto:support@tenant-letter.com" className="text-xs text-gray-600 hover:text-gray-400 transition-colors">Contact</a>
          </div>
          <p className="text-xs text-gray-600 text-center mt-3">
            &copy; {new Date().getFullYear()} TenantShield. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}
